### ISSUE TITLE
Full stage view icon isn't transparent

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme#4]
![image](https://user-images.githubusercontent.com/21194782/83018467-475d1600-a01d-11ea-8dd2-4d79fa42e8ae.png)

This should ideally be replaced in the plugin (needs tracking down where it's coming from) to be transparent, we haven't hit any other icons that have issues on dark mode so best if we can keep the same icons

**Comment by TobiX** [comment]
I first found
https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/853e53b898cb4f93b563ee77084b4f6430eb7ef9/ui/src/main/java/com/cloudbees/workflow/ui/view/WorkflowStageViewAction.java#L40-L42
and was totally confused. Turns out:
https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/9e34c535df0e2c0c1759f509793723acb6e10dd5/ui/src/main/java/com/cloudbees/workflow/ui/view/PluginImpl.java#L42-L43

I don't even 😆

**Comment by timja** [comment]
I still can't see the actual one 👅, but I haven't looked that hard

**Comment by timja** [comment]
Also see https://github.com/jenkinsci/dark-theme/issues/21#issue-626558740

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/86

needs releasing but no point keeping this open

**Comment by oleg-nenashev** [comment]
Maybe it worth creating an org-wide GitHub project for tracking of pull requests, not sure

**Comment by zbynek** [comment]
This seems related to the double icons I get now after plugin update:
![image](https://user-images.githubusercontent.com/1105305/93138008-a46cfc80-f6de-11ea-8b3a-8cec4dc825c5.png)
